# Generated by Django 5.1.5 on 2025-02-03 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_adress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
    ]
